name: Pipeline

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint
    
  faked-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Faked Deploy to Main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          "set NODE_ENV=production"
          "echo 'now deploying to production'"

      - name: Faked Deploy to Test Server
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          "set NODE_ENV=development"
          "echo 'now deploying branch: ${{ github.ref }} to the test server'"
