name: Pipeline

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint
    
    faked-deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Faked Deploy
          run: |
            if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
              echo "now deploying to production"
            else
              echo "now deploying branch: ${{ github.ref }} to the test server"
            fi